export const QK = {
  health: ['health'],
  user: (id) => ['user', id],
  users: (params) => ['users', params],
  customerByUser: (userId) => ['customer', 'by-user', userId],
  customer: (id) => ['customer', id],
  cities: ['cities'],
  city: (id) => ['city', id],
  dealerships: (params) => ['dealerships', params],
  dealership: (id) => ['dealership', id],
  models: (params) => ['models', params],
  model: (id) => ['model', id],
  vehicles: (params) => ['vehicles', params],
  vehicle: (id) => ['vehicle', id],
  orders: (params) => ['orders', params],
  order: (id) => ['order', id],
  customOrders: (params) => ['custom-orders', params],
  customOrder: (id) => ['custom-order', id],
  reviewsByModel: (modelId) => ['reviews', 'model', modelId],
  testDrives: (params) => ['test-drives', params],
  favorites: (customerId) => ['favorites', customerId],
  logs: (params) => ['logs', params],
}
