export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  vehicles: '/vehicles',
  vehicleDetail: (id) => `/vehicles/${id}`,
  models: '/models',
  modelDetail: (id) => `/models/${id}`,
  dealerships: '/dealerships',
  dealershipDetail: (id) => `/dealerships/${id}`,
  company: '/company',
  reviews: '/reviews',
  account: '/account',
  orders: '/account/orders',
  favorites: '/account/favorites',
  testDrives: '/account/test-drives',
  customOrders: '/account/custom-orders',
  staffUsers: '/staff/users',
  staffOrders: '/staff/orders',
  logs: '/staff/logs',
  forbidden: '/forbidden',
}
