export const endpoints = {
  health: '/health',
  auth: {
    signUp: '/auth/signup',
    signIn: '/auth/signin',
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
  },
  users: '/users',
  user: (id) => `/users/${id}`,
  customers: '/customers',
  customer: (id) => `/customers/${id}`,
  customerByUser: (userId) => `/customers/user/${userId}`,
  cities: '/cities',
  city: (id) => `/cities/${id}`,
  dealerships: '/dealerships',
  dealership: (id) => `/dealerships/${id}`,
  dealershipsByCity: (cityId) => `/dealerships/city/${cityId}`,
  dealershipsByCountry: (country) => `/dealerships/country/${country}`,
  models: '/models',
  model: (id) => `/models/${id}`,
  features: '/features',
  feature: (id) => `/features/${id}`,
  featuresByModel: (modelId) => `/features/model/${modelId}`,
  vehicles: '/vehicles',
  vehicle: (id) => `/vehicles/${id}`,
  vehiclesByDealership: (dealershipId) => `/vehicles/dealership/${dealershipId}`,
  orders: '/orders',
  order: (id) => `/orders/${id}`,
  ordersByCustomer: (customerId) => `/orders/customer/${customerId}`,
  ordersByDealership: (dealershipId) => `/orders/dealership/${dealershipId}`,
  orderStatus: (id) => `/orders/${id}/status`,
  customOrders: '/custom-orders',
  customOrder: (id) => `/custom-orders/${id}`,
  customOrdersByCustomer: (customerId) => `/custom-orders/customer/${customerId}`,
  customOrdersByDealership: (dealershipId) => `/custom-orders/dealership/${dealershipId}`,
  customOrderStatus: (id) => `/custom-orders/${id}/status`,
  reviews: '/reviews',
  review: (id) => `/reviews/${id}`,
  reviewsByModel: (modelId) => `/reviews/model/${modelId}`,
  reviewsByCustomer: (customerId) => `/reviews/customer/${customerId}`,
  testDrives: '/test-drives',
  testDrive: (id) => `/test-drives/${id}`,
  testDrivesByCustomer: (customerId) => `/test-drives/customer/${customerId}`,
  testDrivesByDealership: (dealershipId) => `/test-drives/dealership/${dealershipId}`,
  testDrivesByVehicle: (vehicleId) => `/test-drives/vehicle/${vehicleId}`,
  testDriveStatus: (id) => `/test-drives/${id}/status`,
  favorites: '/favorites',
  favoritesByCustomer: (customerId) => `/favorites/customer/${customerId}`,
  logs: '/logs',
}
